on:
  push:
    branches:
      - main

# common public env add inline here
# common secret can be found in secrets
env:
  DOCKER_IMAGE: gcr.io/${{ secrets.GOOGLE_PROJECT_ID }}/deskree_rettiwt

jobs:
  build-deploy:
    runs-on: ${{ matrix.os }}

    strategy:
      matrix:
        os: [ubuntu-latest]
        node: [16]

    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: 'gcloud auth'
        id: 'auth'
        uses: 'google-github-actions/auth@v1'
        with:
          credentials_json: '${{ secrets.GCP_CREDENTIALS }}'

      - name: 'Set up Cloud SDK'
        uses: 'google-github-actions/setup-gcloud@v1'

      - name: 'Use gcloud CLI'
        run: 'gcloud info'

      - name: Setup node env
        uses: actions/setup-node@v2.1.2
        with:
          node-version: 16

      - name: Cache node_modules
        uses: actions/cache@v2
        with:
          path: ~/.npm
          key: ${{ runner.os }}-node-${{ hashFiles('**/package-lock.json') }}
          restore-keys: |
            ${{ runner.os }}-node-

      - name: Install dependencies
        run: npm ci

      - name: GCloud Docker auth
        run: gcloud --quiet auth configure-docker

      - name: Set Staging mode
        run: |-
          echo "Setting Staging mode"
          echo "MODE=production" >> $GITHUB_ENV
          echo "SERVICE_NAME=deskree_rettiwt" >> $GITHUB_ENV

      - name: Create ENV
        uses: SpicyPizza/create-envfile@v1
        with:
          envkey_VITE_APP_DESKREE_PROJECT_ID: ${{ secrets.DESKREE_PROJECT_ID }}
          envkey_VITE_APP_DESKREE_ADMIN_TOKEN: ${{ secrets.DESKREE_ADMIN_TOKEN }}
          file_name: .env

      - name: Build Docker image
        run: |-
          docker build -t $DOCKER_IMAGE:$GITHUB_SHA .

      - name: Push Docker image
        run: |-
          docker push $DOCKER_IMAGE:$GITHUB_SHA

      
